"""
Sumcheck Protocol Naive Implementation in SageMath
"""

from __future__ import annotations
import hashlib

from utils import print_transcript


class SumCheckProtocol:
    """
    Prover and Verifier for the Sum Check protocol.
    """

    def __init__(
        self, F, R,
        polynomial: PolynomialRing, # of type R
        claimed_sum: GF, # of type F
        degree: int
    ) -> None:
        """
        Initializes the SumCheck protocol with a polynomial and the claimed sum.

        Args:
            F (GF): The finite field over which the polynomial is defined.
            R (PolynomialRing): The polynomial ring over the finite field F.
            polynomial (PolynomialRing): The polynomial to be checked.
            claimed_sum (Fp): The sum claimed by the prover over the boolean hypercube.
            degree (int): The degree of the polynomial.
        """

        # Assert that the polynomial is defined over the finite field F
        assert polynomial.base_ring() == F, "Polynomial must be defined over the finite field F"
        
        self.F = F
        self.f = polynomial
        self.variables = R.gens()
        self.H = claimed_sum
        self.degree = degree


    def fiat_shamir_sample(self, input_string: str) -> Fp:
        """
        Samples a random value from the finite field GF(p) using the Fiat-Shamir heuristic.
        The input string is hashed to produce a random value.
        """

        fs_hash = hashlib.sha256(input_string.encode('utf-8')).hexdigest()
        return self.F(int(fs_hash, 16))


    def fiat_shamir_from_polynomials(self, polynomials: list[PolynomialRing]) -> Fp:
        """
        Samples a random value from the finite field GF(p) using the Fiat-Shamir heuristic
        based on the provided polynomials.

        Args:
            polynomials (list[PolynomialRing]): List of polynomials to be used for sampling.

        Returns:
            Fp: A random value from the finite field GF(p).
        """
        
        fs_input = ''.join(str(poly) for poly in polynomials)
        return self.fiat_shamir_sample(fs_input)


    def prove(self) -> dict:
        """
        Prover generates the transcript of the polynomial and the claimed sum.

        Returns:
            dict: A transcript containing the polynomial, claimed sum, random values, and polynomials.
        """

        # Initialize the transcript representing the 
        # interaction between the prover and verifier.
        transcript = {
            'polynomial': self.f,
            'claimed_sum': self.H,
            'random_values': [],
            'polynomials': []
        }

        for j in range(self.degree):
            # The protocol consists of v rounds.
            # Finding polynomial s_j that represents the sum of f over the boolean hypercube
            Rj = PolynomialRing(self.F, 'x')
            x = Rj.gen()
            s_j = Rj.zero()

            for i in range(2**(self.degree-j-1)):
                # Convert i to a binary representation of length degree-j-1
                binary_representation = [(i >> k) & 1 for k in range(self.degree-j-1)]
                # Evaluate the polynomial at this point
                point_value = self.f(*transcript['random_values'][:j], self.variables[j], *binary_representation)
                univariate_poly = point_value.subs({self.variables[j]: x})
                s_j += univariate_poly

            # Append the polynomial s_j to the transcript
            transcript['polynomials'].append(s_j)

            # Sample the random value using Fiat-Shamir heuristic
            random_value = self.fiat_shamir_from_polynomials(transcript['polynomials'])
            transcript['random_values'].append(random_value)

        return transcript

    
    def verify(self, transcript: dict) -> bool:
        """
        Verifier checks the validity of the transcript.

        Args:
            transcript (dict): The transcript generated by the prover.

        Returns:
            bool: True if the claimed sum is valid, False otherwise.
        """
        
        # Decipher the transcript
        H = transcript['claimed_sum']
        f = transcript['polynomial']
        random_values = transcript['random_values']
        polynomials = transcript['polynomials']

        # Assert that random_values is formed correctly using Fiat-Shamir heuristic
        if len(random_values) != self.degree:
            print("Invalid number of random values in the transcript.")
            return False
        for i in range(self.degree):
            if random_values[i] != self.fiat_shamir_from_polynomials(polynomials[:i+1]):
                print(f"Random value at index {i} does not match the Fiat-Shamir sample.")
                return False

        # Assert that each s_r(0) + s_r(1) matches the claimed sum H
        for j in range(self.degree):
            # During the first round, simply check that s_1(0) + s_1(1) = H
            if j == 0:
                s_1 = polynomials[0]
                print(s_1)
                if s_1(0) + s_1(1) != H:
                    print(f"First round sum {s_1(0) + s_1(1)} does not match the claimed sum {H}.")
                    return False
                continue
            
            # For subsequent rounds, check that the sum of the polynomials matches the claimed sum
            s, s_previous = polynomials[j], polynomials[j-1]
            if s(0) + s(1) != s_previous(random_values[j-1]):
                print(f"Round {j} sum {s(0) + s(1)} does not match the previous round's output {s_previous(random_values[j-1])}.")
                return False

        # Final round checks whether f(r) = s_v(r_v)
        last_polynomial = polynomials[-1]
        last_random = random_values[-1]

        if last_polynomial(last_random) != f(*random_values):
            print(f"Final check failed: {last_polynomial(last_random)} != {f(*random_values)}")
            return False
        
        return True


def boolean_hypercube_sum(F, f: PolynomialRing, degree: int) -> GF:
    """
    Computes the sum of the polynomial f over the boolean hypercube {0,1}^v.
    The boolean hypercube is represented by evaluating the polynomial at all
    combinations of 0 and 1 for each variable.
    """

    total_sum = F(0)
    for i in range(1<<degree):
        # Convert i to a binary representation of length 'degree'
        binary_representation = [(i >> j) & 1 for j in range(degree)]
        # Evaluate the polynomial at this point
        point_value = f(*binary_representation)
        total_sum += point_value

    return total_sum


if __name__ == "__main__":
    # Defining the finite field GF(p) where p is a large prime
    p = (1<<31) - 1
    Fp = GF(p)

    # Defining the multivariate polynomial ring over the finite field GF(p)
    v = 10 # Degree of the polynomial
    variable_names = [f'x{i}' for i in range(v)]
    R = PolynomialRing(Fp, names=variable_names)

    # Select a random polynomial and compute H
    f = R.random_element()
    H = boolean_hypercube_sum(Fp, f, degree=v)
    print(f'Prover claims that the sum of {f} over the boolean hypercube of dimension {v} is {H}.')

    protocol = SumCheckProtocol(Fp, R, f, H, degree=v)
    transcript = protocol.prove()
    print_transcript(transcript)

    print(f'Verifier checks the proof: {protocol.verify(transcript)}')