

# This file was *autogenerated* from the file utils.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0)
def pad(polynomial, size):
    polynomial = polynomial.list()
    assert size >= len(polynomial), f"polynomial must be padded to length {size}, got {len(polynomial)}"
    return polynomial + [_sage_const_0 ]*(size-len(polynomial))

